CREATE TABLE IF NOT EXISTS T_RECYCLE_TRANSACTION (
  ID SERIAL PRIMARY KEY,
  TYPE VARCHAR(255) NOT NULL,
  SUBTYPE VARCHAR(255) NOT NULL,
  IMAGE BYTEA NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  DATE DATE NOT NULL,
  --  STATUS VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USER_ID INT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES T_USER(ID) ON DELETE CASCADE
);