CREATE TABLE IF NOT EXISTS T_REWARD_TRANSACTION (
  ID SERIAL PRIMARY KEY,
  VOUCHER_NAME VARCHAR(255) NOT NULL,
  VOUCHER_SERIAL VARCHAR(255) NOT NULL UNIQUE,
  DESCRIPTION VARCHAR(255) NOT NULL,
  VALID_DATE DATE NOT NULL,
  CLAIMED BOOLEAN NOT NULL DEFAULT FALSE,
  CLAIMED_DATE DATE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USER_ID INT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES T_USER(ID) ON DELETE CASCADE
);