CREATE TABLE IF NOT EXISTS T_IMAGE (
  ID SERIAL PRIMARY KEY,
  IMAGE BYTEA NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS T_RECYCLE_TRANSACTION (
  ID SERIAL PRIMARY KEY,
  TYPE VARCHAR(255) NOT NULL,
  SUBTYPE VARCHAR(255) NOT NULL,
  CONFIDENCE VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  DATE DATE NOT NULL,
  --  STATUS VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PREDICTION_ID UUID NOT NULL,
  IMAGE_ID INT NOT NULL,
  USER_ID INT NOT NULL,
  FOREIGN KEY (IMAGE_ID) REFERENCES T_IMAGE(ID) ON DELETE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES T_USER(ID) ON DELETE CASCADE
);