services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    container_name: ${SERVER_CONTAINER_NAME}
    depends_on:
      - db
      - inference
    ports:
      - ${SERVER_PORT}:8080
    env_file:
      - ../.env

  inference:
    build:
      context: ..
      dockerfile: docker/Dockerfile.inference
    container_name: ${INFERENCE_CONTAINER_NAME}
    ports:
      - ${INFERENCE_PORT}:5001
    env_file:
      - ../.env

  db:
    image: postgres:17
    container_name: ${POSTGRES_CONTAINER_NAME_PROD}
    ports:
      - ${DB_PROD_PORT}:5432
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PROD_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_PROD_DB}"]
      interval: 5s
      retries: 5
    # volumes:
    #   - ./sql:/docker-entrypoint-initdb.d
  
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    container_name: migration_runner
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - migrate
    working_dir: /app
    volumes:
      - ../.:/app
    env_file:
      - ../.env
