FROM python:3.13-slim

WORKDIR /src

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY bloobin_model/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY bloobin_model/src .

CMD [ "python3", "-m", "flask", "run", "--host=0.0.0.0" ]
