services:
  # server:

  db:
    image: postgres:17
    container_name: ${POSTGRES_CONTAINER_NAME_PROD}
    ports:
      - ${DB_PROD_PORT}:5432
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PROD_DB}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d