-- T_USER contains user information
CREATE TABLE IF NOT EXISTS T_USER (
  ID SERIAL PRIMARY KEY,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  POINTS INT NOT NULL DEFAULT 0,
);

-- T_RECYCLE_TRANSACTION contains recycle transaction information
CREATE TABLE IF NOT EXISTS T_RECYCLE_TRANSACTION (
  ID SERIAL PRIMARY KEY,
  TYPE VARCHAR(255) NOT NULL
  SUBTYPE VARCHAR(255) NOT NULL,
  IMAGE BYTEA NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  DATE DATE NOT NULL,
  --  STATUS VARCHAR(255) NOT NULL,
  USER_ID INT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES T_USER(ID) ON DELETE CASCADE
);

-- T_REWARD_TRANSACTION contains reward transaction information
CREATE TABLE IF NOT EXISTS T_REWARD_TRANSACTION (
  ID SERIAL PRIMARY KEY,
  VOUCHER_NAME VARCHAR(255) NOT NULL,
  VOUCHER_SERIAL VARCHAR(255) NOT NULL UNIQUE,
  DESCRIPTION VARCHAR(255) NOT NULL,
  VALID_DATE DATE NOT NULL,
  CLAIMED BOOLEAN NOT NULL DEFAULT FALSE,
  USER_ID INT NOT NULL,
  CLAIMED_DATE DATE,
  FOREIGN KEY (USER_ID) REFERENCES T_USER(ID) ON DELETE CASCADE
);

-- T_VOUCHER_CATALOGUE contains voucher catalogue information that can be
-- redeemed by user using points
CREATE TABLE IF NOT EXISTS T_VOUCHER_CATALOGUE (
  ID SERIAL PRIMARY KEY,
  VOUCHER_NAME VARCHAR(255) NOT NULL UNIQUE,
  COST INT NOT NULL
);
